---
- hosts: HRSAPtomcattest
  vars:
    java_home: /opt/java/
  tasks: 
     #杀死服务判断
     # O  K
     - name: check java running status...
       shell: ps -ef | grep java | grep -v grep | wc -l
       register: java_process_count
     - debug:
       msg: "java_process_count is {{java_process_count.stdout}}"
     - name: shutdown java process pid...
       shell: pkill java
       when: java_process_count.stdout > "0"

#OK
     #删除jar包
     - name: delete file
       file: path={{ java_home }}{{ item }} state=absent
       with_items:
         - ehr-service/ehr-service.jar
         - auth-service/auth-service.jar
         - discovery-service/discovery-service.jar
         - ehr-download/ehr-download.jar
         - gateway-service/gateway-service.jar
         - zipkin-service/zipkin-service.jar 

#OK  复制jar
     - name: copy jar file
       synchronize: src=/deploy/21HRSAPtomcattest/new_deploy/{{ item.key }} dest={{ java_home }}{{ item.value }} copy=no
       with_items:
         - { key: "ehr-service.jar", value: "ehr-service/"}
         - { key: "auth-service.jar", value: "auth-service"}
         - { key: "discovery-service.jar", value: "discovery-service"}
         - { key: "ehr-download.jar", value: "ehr-download"}
         - { key: "gateway-service.jar", value: "gateway-service"}
         - { key: "zipkin-service.jar", value: "zipkin-service"}
   
   
   
#配置文件
     - name: copy config file
       synchronize: src={{ item.key }}  dest={{ java_home }}{{ item.value }}
       with_items:
         - { key: "/deploy/21HRSAPtomcattest/new_deploy/pdfTempl" value: "ehr-service/"}
 

  
#OK 启动服务     
     - name: startup service
       command: /opt/java/scripts/startup_java_ehr-service.sh
     - name: startup service
       command: /opt/java/scripts/startup_java_discovery-service.sh
     - name: startup service
       command: /opt/java/scripts/startup_java_auth-service.sh
     - name: startup service
       command: /opt/java/scripts/startup_java_gateway-service.sh
     - name: startup service
       command: /opt/java/scripts/startup_java_zipkin-service.sh
     - name: startup service
       command: /opt/java/scripts/startup_java_ehr-download.sh



